# frozen_string_literal: true

# Integration smoke that exercises SchemaDiff against schema.rb output
# generated by a real ActiveRecord version. Used by CI to verify the lib
# stays compatible across the Ruby x Rails matrix.
#
# Pulls activerecord at the version specified by RAILS_VERSION (default: 7.1.0)
# via bundler/inline so we do not have to commit a Gemfile.lock.

require "bundler/inline"

rails_version = ENV.fetch("RAILS_VERSION", "7.1.0")

gemfile do
  source "https://rubygems.org"
  gem "activerecord", rails_version
  gem "sqlite3", ">= 1.4"
  gem "minitest", "~> 5.0"
end

require "active_record"
require "minitest/autorun"
require "stringio"
require_relative "../lib/schema_diff"

ActiveRecord::Base.establish_connection(adapter: "sqlite3", database: ":memory:")
ActiveRecord::Migration.verbose = false

class IntegrationTest < Minitest::Test
  def setup
    drop_all_tables
  end

  def test_schema_round_trip_matches
    define_base_schema
    dumped = dump_schema
    result = SchemaDiff.diff(head: dumped, actual: dumped)
    assert result.empty?, "round-trip dump should be empty: #{result.text}"
  end

  def test_added_column_via_migration_is_detected
    define_base_schema
    head_schema = dump_schema

    migration = Class.new(ActiveRecord::Migration::Current) do
      def change
        add_column :orders, :status, :string, null: false, default: "pending"
      end
    end
    migration.new.migrate(:up)

    actual_schema = dump_schema
    result = SchemaDiff.diff(head: head_schema, actual: actual_schema)

    refute result.empty?, "should detect added column"
    assert_includes result.tables, "orders"
    refute_includes result.tables, "users"
  end

  private

  def define_base_schema
    ActiveRecord::Schema.define(version: 1) do
      create_table :users, force: :cascade do |t|
        t.string :name, null: false
        t.string :email, null: false
        t.timestamps
      end

      create_table :orders, force: :cascade do |t|
        t.bigint :user_id, null: false
        t.integer :amount_cents, null: false
        t.timestamps
        t.index :user_id
      end
    end
  end

  def dump_schema
    io = StringIO.new
    ActiveRecord::SchemaDumper.dump(ActiveRecord::Base.connection, io)
    io.string
  end

  def drop_all_tables
    conn = ActiveRecord::Base.connection
    conn.tables.each { |t| conn.drop_table(t, if_exists: true) }
  end
end
